spring.application.name=transbras

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

app.security.jwt.secret=${AUTH_SECRET}
app.security.admin.password=${ADMIN_PASSWORD}